version: '3'
services:
  nodejs:
    build:
      context: ./node
      dockerfile: Dockerfile.nodejs
    image: andremfagundes/fullcycledockernode
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'
    networks:
      - minha-rede
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: andremfagundes/fullcycledockernginx
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - minha-rede
    depends_on:
      - nodejs
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - minha-rede
networks:
  minha-rede:
